stages:
  - module-pipelines
  - build
  - notify
  - test
  - release



variables:
  DOCKER_REGISTRY: ""
  ART_DOWNLOAD_URL: ""
  SLACK_URL: ""
  SONAR_PROJECT_KEY_BE: ""
  SONAR_PROJECT_KEY_FE: ""
  SONARQUBE_URL: ""
  SONAR_LOGIN: ""
  VERSION: 1.0.${CI_PIPELINE_ID}
  DEV_USER:
  DEV_HOST:
  NEXUS_ART_URL: ""
  PSQL_HOST:
  PSQL_PORT:
  PSQL_DBNAME:
  PSQL_USER:
  PSQL_PASSWORD:
  MONGO_USER:
  MONGO_PASSWORD:
  MONGO_HOST:
  MONGO_DATABASE:


frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes: # как только происходит изменение в папке frontend, запускается дочерний пайплайн, который лежит в этой папке
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend # depend нужен, если какой-нибудь дочерний пайплайн свалился, мы знали, что общий пайплайн тоже идёт с ошибкой
  only:
    changes: # как только происходит изменение в папке backend, запускается дочерний пайплайн, который лежит в этой папке
      - backend/**/*

